export default {
  Dark_Theme: 'DARK_THEME',
  Profile_Photo: 'Profile_Photo',
  Reset_Store: 'Reset_Store',
  Is_Login: 'Is_Login',
  SHOW_INTRO: 'SHOW_INTRO',
  COMPLETE_PROFILE_DATA: 'COMPLETE_PROFILE_DATA',
  LATER_BUTTON_USER_DATA: 'LATER_BUTTON_USER_DATA',
  User_ID: 'User_ID',
  CUSTOM_WORKOUT_DATA: 'CUSTOM_WORKOUT_DATA',
  CURRENT_WORKOUT_DATA: 'CURRENT_WORKOUT_DATA',
  ALL_WORKOUTS_DATA: 'ALL_WORKOUTS_DATA',
  User_Profile_Data:'User_Profile_Data',
  Mindset_Data:'Mindset_Data',
  MindSetConsent:' MindSetConsent',
  LogOut:'LogOut',
  ALL_MEAL_DATA: 'ALL_MEAL_DATA',
  COUNT: 'COUNT',
};
