export const CountryCurrencies: any = {
    "United States": "$",
    "India": "₹",
    "United Kingdom": "£",
    "Eurozone": "€",
    "Japan": "¥",
    "Australia": "A$",
    "Canada": "C$",
    "Switzerland": "CHF",
    "China": "¥",
    "Russia": "₽",
    "South Africa": "R",
    "Brazil": "R$",
    "Mexico": "$",
    "New Zealand": "NZ$",
    "Singapore": "S$",
    "Turkey": "₺",
    "South Korea": "₩",
    "Indonesia": "Rp",
    "Malaysia": "RM",
    "Philippines": "₱",
    "Vietnam": "₫",
    "Thailand": "฿",
    "Pakistan": "₨",
    "Bangladesh": "৳",
    "Egypt": "£", // Egyptian Pound
    "Israel": "₪",
    "Saudi Arabia": "ر.س", // Saudi Riyal
    "United Arab Emirates": "د.إ", // UAE Dirham
    "Norway": "kr",
    "Denmark": "kr",
    "Sweden": "kr",
    "Hungary": "Ft",
    "Czech Republic": "Kč",
    "Romania": "lei",
    "Bulgaria": "лв", // Bulgarian Lev
    "Serbia": "дин.", // Serbian Dinar
    "Croatia": "kn", // Croatian Kuna
    "Iceland": "kr",
    "Kazakhstan": "₸",
    "Nigeria": "₦",
    "Ghana": "₵",
    "Colombia": "$",
    "Chile": "$",
    "Peru": "S/.",
    "Costa Rica": "₡",
    "Jamaica": "J$",
    "Trinidad and Tobago": "TT$",
    "Barbados": "Bds$",
    "Bahamas": "B$",
    "Fiji": "FJ$",
    "Papua New Guinea": "K",
    "Tanzania": "TSh",
    "Uganda": "UGX",
    "Zambia": "ZK",
    "Botswana": "P",
    "Mauritius": "₨",
    "Sri Lanka": "Rs",
    "Lebanon": "ل.ل", // Lebanese Pound
    "Syria": "ل.س", // Syrian Pound
    "Oman": "ر.ع.", // Omani Rial
    "Qatar": "ر.ق", // Qatari Rial
    "Kuwait": "د.ك", // Kuwaiti Dinar
    "Maldives": "MVR",
    "Mongolia": "₮",
    "Brunei": "B$",
    "Eswatini": "E",
    "Lesotho": "L",
    "Mauritania": "UM",
    "Sao Tome and Principe": "Db",
    "Comoros": "CF",
    "Djibouti": "Fdj",
    "Central African Republic": "FCFA",
    "Congo, Democratic Republic of the": "FC",
    "Congo, Republic of the": "FCFA",
    "Equatorial Guinea": "FCFA",
    "Gabon": "FCFA",
    "Malawi": "MK",
    "Niger": "FCFA",
    "Rwanda": "RWF",
    "Sierra Leone": "Le",
    "Togo": "FCFA",
    "Vanuatu": "VT",
    "Solomon Islands": "SI$",
    "Kiribati": "A$",
    "Micronesia": "FM$",
    "Marshall Islands": "M",
    "Palau": "A$",
    // Add more countries and their currency signs as needed
  };