export const localImage = {
  Lock: require('../Icon/Images/NewImage/Lock.png'),
  Message: require('../Icon/Images/NewImage/Message.png'),
  GOOGLE: require('../Icon/Images/NewImage/google.png'),
  PROFILE: require('../Icon/Images/NewImage/Profile.png'),
  SplashText: require('../Icon/Images/NewImage/SplashText.png'),
  CircleSplash: require('../Icon/Images/NewImage/CircleSplash.png'),
  BGSplash: require('../Icon/Images/NewImage/BGSplash.png'),
  LogoSplash: require('../Icon/Images/NewImage/LogoSplash.png'),
  Verify: require('../Icon/Images/NewImage/verify.png'),
  Cross: require('../Icon/Images/NewImage/Cross.png'),
  Step1: require('../Icon/Images/NewImage/Pado1.png'),
  Step2: require('../Icon/Images/NewImage/Pado2.png'),
  Step3: require('../Icon/Images/NewImage/Pado3.png'),
  INFO: require('../Icon/Images/NewImage/GroupInfo.png'),
  Noimage: require('../Icon/Images/NewImage/no-pictures.png'),
  Watch: require('../Icon/Images/NewImage/watch.png'),
  Congrats: require('../Icon/Images/NewImage/Congrats.png'),
  Action: require('../Icon/Images/NewImage/Action.png'),
  Clock: require('../Icon/Images/NewImage/Clock.png'),
  Complete: require('../Icon/Images/NewImage/Complete.png'),
  Play2: require('../Icon/Images/NewImage/playButton.png'),
  Farwed: require('../Icon/Images/NewImage/Farwed.png'),
  Play3: require('../Icon/Images/NewImage/Play3.png'),
  Target: require('../Icon/Images/NewImage/Target.png'),
  Location: require('../Icon/Images/NewImage/Location.png'),
  WithoutEquipPerson: require('../Icon/Images/NewImage/WithoutEquipementPerson.png'),
  User: require('../Icon/Images/NewImage/User.png'),
  Send: require('../Icon/Images/NewImage/send.png'),
  Rest: require('../Icon/Images/NewImage2/restDay.png'),
  ChatHistory: require('../Icon/Images/NewImage/chatHistory.png'),
  Feedback: require('../Icon/Images/NewImage/Feedback.png'),
  Fire1: require('../Icon/Images/NewImage/Fire1.png'),
  Clock1: require('../Icon/Images/NewImage/Clock1.png'),
  AppleLogo: require('../Icon/Images/NewImage/apple.png'),
  avt: require('../Icon/Images/NewImage/Avatar.png'),

  RedTick: require('../Icon/Images/NewImage2/GreenTick.png'),
  ClockGrey: require('../Icon/Images/NewImage/ClockGrey.png'),

  NewWorkout: require('../Icon/Images/NewImage2/NewWorkout.png'),
  Createworkout: require('../Icon/Images/NewImage2/createworkout.png'),
  CalenderNew: require('../Icon/Images/NewImage2/canender.png'),
  Plus: require('../Icon/Images/NewImage2/plus.png'),
  Minus: require('../Icon/Images/NewImage2/Minus.png'),
  Next: require('../Icon/Images/NewImage2/next.png'),
  Home: require('../Icon/Images/NewImage2/Home.png'),
  Profile: require('../Icon/Images/NewImage2/Profile.png'),
  Workout: require('../Icon/Images/NewImage2/Workout.png'),
  Reports: require('../Icon/Images/NewImage2/Reports.png'),
  MyPlans: require('../Icon/Images/NewImage2/MyPlans.png'),
  HomeRed: require('../Icon/Images/NewImage2/HomeRed.png'),
  ProfileRed: require('../Icon/Images/NewImage2/ProfileRed.png'),
  WorkoutRed: require('../Icon/Images/NewImage2/WorkoutRed.png'),
  ReportsRed: require('../Icon/Images/NewImage2/ReportsRed.png'),
  MyPlansRed: require('../Icon/Images/NewImage2/MyPlansRed.png'),
  PlayIcon: require('../Icon/Images/NewImage2/PlayIcon.png'),
  NewPen: require('../Icon/Images/NewImage2/NewPen.png'),
  Bell: require('../Icon/Images/NewImage2/bell.png'),
  Planning: require('../Icon/Images/NewImage2/planning.png'),
  NewPrfile: require('../Icon/Images/NewImage2/NewProfile.png'),
  NSounds: require('../Icon/Images/NewImage2/NSounds.png'),
  NMusic: require('../Icon/Images/NewImage2/NMusic.png'),
  NReport: require('../Icon/Images/NewImage2/ReportProfile.png'),
  NContact: require('../Icon/Images/NewImage2/NContact.png'),
  NPrivacy: require('../Icon/Images/NewImage2/NPrivacy.png'),
  FAQ: require('../Icon/Images/NewImage2/faq.png'),
  REPORT: require('../Icon/Images/NewImage2/report.png'),
  NPolicy: require('../Icon/Images/NewImage2/NDocument.png'),
  NRate: require('../Icon/Images/NewImage2/NRate.png'),
  NDelete: require('../Icon/Images/NewImage2/NDelete.png'),
  NLogOut: require('../Icon/Images/NewImage2/NLogout.png'),
  NOWORKOUT: require('../Icon/Images/NewImage2/test.gif'),
  DisplayOn: require('../Icon/Images/NewImage2/DisplayOn.png'),
  Exercise_Info: require('../Icon/Images/NewImage2/Exercise_Info.png'),
  Exercise_List: require('../Icon/Images/NewImage2/Exercise_List.png'),
  MaleNew: require('../Icon/Images/NewImage2/MaleN.png'),
  FemaleNew: require('../Icon/Images/NewImage2/FemaleNew.png'),
  Alert: require('../Icon/Images/NewImage2/Alert.png'),
  RecommendFitme: require('../Icon/Images/InAppRewards/RecommendFitme.png'),
  ChangePlan: require('../Icon/Images/InAppRewards/ChangePlan.png'),
  Trophy: require('../Icon/Images/InAppRewards/Trophy.png'),
  FitCoin: require('../Icon/Images/InAppRewards/FitCoin.png'),
  completed: require('../Icon/Images/InAppRewards/Completed.png'),
  Missed: require('../Icon/Images/InAppRewards/Missed.png'),
  EditPen: require('../Icon/Images/InAppRewards/edit.png'),
  BasicPlan: require('../Icon/Images/InAppRewards/BasicPlan.png'),
  MediumPlan: require('../Icon/Images/InAppRewards/MediumPlan.png'),
  PremiumPlan: require('../Icon/Images/InAppRewards/PremiumPlan.png'),
  PlanBenifits: require('../Icon/Images/InAppRewards/PlanBenifits.png'),
  NameUpdateModal: require('../Icon/Images/InAppRewards/NameUpdateModal.png'),
  Reward_icon: require('../Icon/Images/InAppRewards/Reward_icon.png'),
  RTermsLogo: require('../Icon/Images/InAppRewards/RTermslogo.png'),
  Intro1: require('../Icon/Images/NewImage2/intro1.png'),
  TranslateIntro: require('../Icon/Images/NewImage2/TranslateIntro.png'),
  Intro2: require('../Icon/Images/NewImage2/intro2.png'),
  Intro3: require('../Icon/Images/NewImage2/intro3.png'),
  ExercisePlay: require('../Icon/Images/NewImage2/ExercisePlay.png'),
  IntroJSON: require('../Icon/Images/InAppRewards/IntroJSON.json'),
  Reward_icon1: require('../Icon/Images/InAppRewards/Reward_icon1.png'),
  fullsizebanner: require('../Icon/Images/InAppRewards/fullsizeBanner.png'),
  Rating1: require('../Icon/Images/InAppRewards/Cry_image.png'),
  Rating2: require('../Icon/Images/InAppRewards/Sad_image.png'),
  Rating3: require('../Icon/Images/InAppRewards/Happy_image.png'),
  Rating4: require('../Icon/Images/InAppRewards/Cool_image.png'),
  Rating5: require('../Icon/Images/InAppRewards/Loveit_image.png'),
  StreakImg: require('../Icon/Images/InAppRewards/StreakImg.png'),
  Streak: require('../Icon/Images/InAppRewards/streak.png'),
  StreakBreak: require('../Icon/Images/InAppRewards/Streakbreak.png'),
  Offer_Img: require('../Icon/Images/InAppRewards/Offer_ins.png'),
  Refer_banner: require('../Icon/Images/InAppRewards/Refer_banner.png'),
  Referral_Coin_Banner: require('../Icon/Images/InAppRewards/Referral_Coin_Banner.png'),
  Bronze: require('../Icon/Images/InAppRewards/Bronze.png'),
  Silver: require('../Icon/Images/InAppRewards/Silver.png'),
  RefferalOutline: require('../Icon/Images/InAppRewards/RefferalOutline.png'),
  closeButton: require('../Icon/Images/InAppRewards/closeButton.png'),
  RefferalCodeImg: require('../Icon/Images/InAppRewards/RefferalCode.png'),
  warning: require('../Icon/Images/InAppRewards/warning.png'),
  danger: require('../Icon/Images/InAppRewards/danger.png'),
  success: require('../Icon/Images/InAppRewards/success.png'),
  greenStreak: require('../Icon/Images/InAppRewards/GreenStreak.png'),
  line: require('../Icon/Images/InAppRewards/line.png'),
  breathingSound: require('../Icon/Images/breathing.mp3'),
  VolumeUp: require('../Icon/Images/InAppRewards/Volumeup.json'),
  focusAnimation: require('../Icon/Images/InAppRewards/focusAnimation.json'),
  heartAnimation: require('../Icon/Images/InAppRewards/heartAnimation.json'),
  caution: require('../Icon/Images/InAppRewards/caution.png'),
  infoCircle: require('../Icon/Images/InAppRewards/info-circle.png'),
  cornerimg: require('../Icon/Images/InAppRewards/cornerimg.png'),
  calender: require('../Icon/Images/InAppRewards/calender.png'),
  pause_icon: require('../Icon/Images/InAppRewards/stay_icon.png'),
  delay_icon: require('../Icon/Images/InAppRewards/delay.png'),
  repeat_icon: require('../Icon/Images/InAppRewards/Repeat_icon.png'),
  skip_icon: require('../Icon/Images/InAppRewards/Skip_icon.png'),
  heart_icon: require('../Icon/Images/InAppRewards/heart_icon.png'),
  breath_icon: require('../Icon/Images/InAppRewards/breath_icon.png'),
  starCorner: require('../Icon/Images/InAppRewards/starCorner.png'),
  gift_icon: require('../Icon/Images/InAppRewards/gift_icon.png'),
  person_profile: require('../Icon/Images/InAppRewards/person-profile.png'),
  persons: require('../Icon/Images/InAppRewards/persons.png'),
  person_plus: require('../Icon/Images/InAppRewards/person-plus.png'),
  calender_icon: require('../Icon/Images/InAppRewards/calender_icon.png'),
  daymiss_icon: require('../Icon/Images/InAppRewards/daymiss_icon.png'),
  tooltip_outline: require('../Icon/Images/InAppRewards/tooltip_outline.png'),
  offer_girl: require('../Icon/Images/InAppRewards/offer_girl.png'),
  cardio_banner: require('../Icon/Images/InAppRewards/cardio_banner.png'),
  reffer_banner: require('../Icon/Images/InAppRewards/reffer_banner.png'),
  breathe_banner: require('../Icon/Images/InAppRewards/breathe_banner.png'),
  event_banner1: require('../Icon/Images/InAppRewards/event_banner1.png'),
  event_banner2: require('../Icon/Images/InAppRewards/event_banner2.png'),
  greyStreak: require('../Icon/Images/InAppRewards/greyStreak.png'),
  cardioImage: require('../Icon/Images/InAppRewards/cardioImage.png'),
  breahteImage: require('../Icon/Images/InAppRewards/breatheImage.png'),
  trophyIcon: require('../Icon/Images/InAppRewards/trophyIcon.png'),
  NoMeal:require('../Icon/Images/InAppRewards/NoMeal.png'),
  ChatBotImage:require('../Icon/Images/InAppRewards/ChatBotImage.png'),
  StepGuidHead:require('../Icon/Images/InAppRewards/StepGuidHead.png'),
  StepHealth:require('../Icon/Images/InAppRewards/StepHealth.png'),
  StepTrophy:require('../Icon/Images/InAppRewards/StepTrophy.png'),
  StepBadge:require('../Icon/Images/InAppRewards/StepBadge.png'),
  Hourglass:require('../Icon/Images/InAppRewards/Hourglass.png'),
  NormalRank: require('../Icon/Images/InAppRewards/NormalRank.png'),
  cautionLottie:require('../Icon/Images/InAppRewards/cautionLottie.json'),
  celebrationAnimation:require('../Icon/Images/InAppRewards/celebration.json'),
  celebrationTrophy:require('../Icon/Images/InAppRewards/celebrationTrophy.png'),
  startCorner1:require('../Icon/Images/InAppRewards/starCorner1.png'),
  rankImage:require('../Icon/Images/InAppRewards/rankImage.png'),
  notification_permission:require('../Icon/Images/NewImage/notification_permission.png'),
  gallery_permission:require('../Icon/Images/NewImage/gallery_permission.png'),
  location_permission:require('../Icon/Images/NewImage/location_permission1.png'),
  health_permission:require('../Icon/Images/NewImage/health_permission.png')
};
