export const localImage = {
  logo: require('../Icon/Images/icons/logo.png'),
  color_image: require('../Icon/Images/color-image.png'),
  nextButton: require('../Icon/Images/next.png'),
  homeImg: require('../Icon/Images/icons/bg.jpg'),
  blogIcon: require('../Icon/Images/blogIcon.png'),
  logo1: require('../Icon/Images/icons/logo.png'),
  maleIcon: require('../Icon/Images/male.jpg'),
  addIcon: require('../Icon/Images/addIcon.png'),
  dw1: require('../Icon/Images/DwaderImage/n1.png'),
  dw2: require('../Icon/Images/DwaderImage/n2.png'),
  dw3: require('../Icon/Images/DwaderImage/n3.png'),
  dw4: require('../Icon/Images/DwaderImage/n4.png'),
  dw5: require('../Icon/Images/DwaderImage/n5.png'),
  dw6: require('../Icon/Images/DwaderImage/n6.png'),
  
  dw8: require('../Icon/Images/DwaderImage/n8.png'),
  dw9: require('../Icon/Images/DwaderImage/n9.png'),
  avt: require('../Icon/Images/DwaderImage/Avatar.png'),
  dw10: require('../Icon/Images/DwaderImage/n10.png'),
  dw11: require('../Icon/Images/DwaderImage/n11.png'),
  Lock: require('../Icon/Images/NewImage/Lock.png'),
  Message: require('../Icon/Images/NewImage/Message.png'),
  EYE: require('../Icon/Images/NewImage/eye.png'),
  EYE1: require('../Icon/Images/NewImage/eye1.png'),
  FACEBOOK: require('../Icon/Images/NewImage/facebook.png'),
  GOOGLE: require('../Icon/Images/NewImage/google.png'),
  PROFILE: require('../Icon/Images/NewImage/Profile.png'),
  GENDER: require('../Icon/Images/NewImage/Gender.png'),
  PathChargeLevel: require('../Icon/Images/NewImage/PathChargeLevel.png'),
  BACK: require('../Icon/Images/NewImage/back.png'),

  BELL: require('../Icon/Images/NewImage/bell.png'),
  Calories: require('../Icon/Images/NewImage/Calories.png'),
  Step: require('../Icon/Images/NewImage/Step.png'),
  BlueTick: require('../Icon/Images/NewImage/BlueTick.png'),
  Profile4: require('../Icon/Images/NewImage/Profile4.png'),
  Documents: require('../Icon/Images/NewImage/Document.png'),
  Heart: require('../Icon/Images/NewImage/heart-icon.png'),
  Shield: require('../Icon/Images/NewImage/Shield.png'),
  reminder: require('../Icon/Images/NewImage/Vector3.png'),
  History: require('../Icon/Images/NewImage/tabler_history.png'),
  Documents: require('../Icon/Images/NewImage/Document.png'),
  Pen: require('../Icon/Images/NewImage/Pen.png'),
  Profile3: require('../Icon/Images/NewImage/Profile.png'),
  SplashText: require('../Icon/Images/NewImage/SplashText.png'),
  Ellipse: require('../Icon/Images/NewImage/Ellipse.png'),
  Verify: require('../Icon/Images/NewImage/verify.png'),
  Solder: require('../Icon/Images/NewImage/Solder.png'),
  Solder1: require('../Icon/Images/NewImage/Sloder1.png'),
  BULB: require('../Icon/Images/NewImage/emojione_light-bulb.png'),
  SelectLevel: require('../Icon/Images/NewImage/SelectLevel.png'),
  Meditation_yes: require('../Icon/Images/NewImage/Meditation_yes.png'),
  Cross: require('../Icon/Images/NewImage/Cross.png'),
  GroupHome: require('../Icon/Images/NewImage/GroupHome.png'),
  foot: require('../Icon/Images/NewImage/noun-walk.png'),
  Person_Walk: require('../Icon/Images/NewImage/Person_walking.png'),
  Person_Sleep: require('../Icon/Images/NewImage/noun-sleeping.png'),
  Normal: require('../Icon/Images/NewImage/Normal.png'),
  Stress: require('../Icon/Images/NewImage/Stress.png'),
  Anxiety: require('../Icon/Images/NewImage/Anxiety.png'),
  Depression: require('../Icon/Images/NewImage/Depression.png'),
  face1: require('../Icon/Images/NewImage/happy-face.png'),
  face2: require('../Icon/Images/NewImage/stressed.png'),
  face3: require('../Icon/Images/NewImage/stressedAnxiety.png'),
  face4: require('../Icon/Images/NewImage/stressedDepression.png'),
  lvl1:require('../Icon/Images/NewImage/lvl1.png'),
  lvl2:require('../Icon/Images/NewImage/lvl2.png'),
  lvl3:require('../Icon/Images/NewImage/lvl3.png'),
  WithEquipment: require('../Icon/Images/NewImage/WithE.png'),
  WithoutEquipment: require('../Icon/Images/NewImage/WithoutE.png'),
  MaleHeight: require('../Icon/Images/NewImage/MaleHeight.png'),
  FemaleHeight: require('../Icon/Images/NewImage/FemaleHeight.png'),
  MaleWeight: require('../Icon/Images/NewImage/MaleWeight.png'),
  FemaleWeight: require('../Icon/Images/NewImage/FemaleWeight.png'),
  Leg: require('../Icon/Images/NewImage/Leg.png'),
  Abs: require('../Icon/Images/NewImage/Abs.png'),
  Chest: require('../Icon/Images/NewImage/Chest.png'),
  Abs2: require('../Icon/Images/NewImage/Abs2.png'),
  Leg2: require('../Icon/Images/NewImage/Leg2.png'),
  Alocol_yes:require('../Icon/Images/NewImage/Alcohol_yes.png'),
  Alocol_no:require('../Icon/Images/NewImage/Alcohol_no.png'),
  Alocol_Dnt:require('../Icon/Images/NewImage/Not_to_say.png'),
  Money:require('../Icon/Images/NewImage/money.png'),
  Step1:require('../Icon/Images/NewImage/Pado1.png'),
  Step2:require('../Icon/Images/NewImage/Pado2.png'),
  Step3:require('../Icon/Images/NewImage/Pado3.png'),
  Backupimg:require('../Icon/Images/NewImage/Backup.png'),
  DeleteAcc:require('../Icon/Images/NewImage/Delete_account.png'),
  RateStar:require('../Icon/Images/NewImage/rate_star.png'),
  Soundimg:require('../Icon/Images/NewImage/Soundimg.png'),
  INFO:require('../Icon/Images/NewImage/GroupInfo.png'),
  Play:require('../Icon/Images/NewImage/play.png'),
  dw7: require('../Icon/Images/NewImage/n7.png'),
  GymImage: require('../Icon/Images/NewImage/GymImage.png'),
  Noimage: require('../Icon/Images/NewImage/no-pictures.png'),
  Watch: require('../Icon/Images/NewImage/watch.png')



};
