export const localImage = {
  Lock: require('../Icon/Images/NewImage/Lock.png'),
  Message: require('../Icon/Images/NewImage/Message.png'),
  EYE: require('../Icon/Images/NewImage/eye.png'),
  EYE1: require('../Icon/Images/NewImage/eye1.png'),
  FACEBOOK: require('../Icon/Images/NewImage/facebook.png'),
  GOOGLE: require('../Icon/Images/NewImage/google.png'),
  PROFILE: require('../Icon/Images/NewImage/Profile.png'),
  GENDER: require('../Icon/Images/NewImage/Gender.png'),
  PathChargeLevel: require('../Icon/Images/NewImage/PathChargeLevel.png'),
  BACK: require('../Icon/Images/NewImage/back.png'),
  BELL: require('../Icon/Images/NewImage/bell.png'),
  Step: require('../Icon/Images/NewImage/Step.png'),
  BlueTick: require('../Icon/Images/NewImage/BlueTick.png'),
  Profile4: require('../Icon/Images/NewImage/Profile4.png'),
  Documents: require('../Icon/Images/NewImage/Document.png'),
  Heart: require('../Icon/Images/NewImage/heart-icon.png'),
  Shield: require('../Icon/Images/NewImage/Shield.png'),
  reminder: require('../Icon/Images/NewImage/Vector3.png'),
  History: require('../Icon/Images/NewImage/tabler_history.png'),
  Documents: require('../Icon/Images/NewImage/Document.png'),
  Pen: require('../Icon/Images/NewImage/Pen.png'),
  Profile3: require('../Icon/Images/NewImage/Profile.png'),
  SplashText: require('../Icon/Images/NewImage/SplashText.png'),
  Ellipse: require('../Icon/Images/NewImage/Ellipse.png'),
  Verify: require('../Icon/Images/NewImage/verify.png'),
  Solder: require('../Icon/Images/NewImage/Solder.png'),
  Solder1: require('../Icon/Images/NewImage/Sloder1.png'),
  BULB: require('../Icon/Images/NewImage/emojione_light-bulb.png'),
  SelectLevel: require('../Icon/Images/NewImage/SelectLevel.png'),
  Meditation_yes: require('../Icon/Images/NewImage/Meditation_yes.png'),
  Cross: require('../Icon/Images/NewImage/Cross.png'),
  GroupHome: require('../Icon/Images/NewImage/GroupHome.png'),
  foot: require('../Icon/Images/NewImage/noun-walk.png'),
  Person_Walk: require('../Icon/Images/NewImage/Person_walking.png'),
  Person_Sleep: require('../Icon/Images/NewImage/noun-sleeping.png'),
  Normal: require('../Icon/Images/NewImage/Normal.png'),
  Stress: require('../Icon/Images/NewImage/Stress.png'),
  Anxiety: require('../Icon/Images/NewImage/Anxiety.png'),
  Depression: require('../Icon/Images/NewImage/Depression.png'),
  face1: require('../Icon/Images/NewImage/happy-face.png'),
  face2: require('../Icon/Images/NewImage/stressed.png'),
  face3: require('../Icon/Images/NewImage/stressedAnxiety.png'),
  face4: require('../Icon/Images/NewImage/stressedDepression.png'),
  lvl1: require('../Icon/Images/NewImage/lvl1.png'),
  lvl2: require('../Icon/Images/NewImage/lvl2.png'),
  lvl3: require('../Icon/Images/NewImage/lvl3.png'),
  WithEquipment: require('../Icon/Images/NewImage/WithE.png'),
  WithoutEquipment: require('../Icon/Images/NewImage/WithoutE.png'),
  MaleHeight: require('../Icon/Images/NewImage/MaleHeight.png'),
  FemaleHeight: require('../Icon/Images/NewImage/FemaleHeight.png'),
  MaleWeight: require('../Icon/Images/NewImage/MaleWeight.png'),
  FemaleWeight: require('../Icon/Images/NewImage/FemaleWeight.png'),
  Leg: require('../Icon/Images/NewImage/Leg.png'),
  Abs: require('../Icon/Images/NewImage/Abs.png'),
  Chest: require('../Icon/Images/NewImage/Chest.png'),
  Abs2: require('../Icon/Images/NewImage/Abs2.png'),
  Leg2: require('../Icon/Images/NewImage/Leg2.png'),
  Alocol_yes: require('../Icon/Images/NewImage/Alcohol_yes.png'),
  Alocol_no: require('../Icon/Images/NewImage/Alcohol_no.png'),
  Alocol_Dnt: require('../Icon/Images/NewImage/Not_to_say.png'),
  Money: require('../Icon/Images/NewImage/money.png'),
  Step1: require('../Icon/Images/NewImage/Pado1.png'),
  Step2: require('../Icon/Images/NewImage/Pado2.png'),
  Step3: require('../Icon/Images/NewImage/Pado3.png'),
  Backupimg: require('../Icon/Images/NewImage/Backup.png'),
  DeleteAcc: require('../Icon/Images/NewImage/Delete_account.png'),
  RateStar: require('../Icon/Images/NewImage/rate_star.png'),
  Soundimg: require('../Icon/Images/NewImage/Soundimg.png'),
  INFO: require('../Icon/Images/NewImage/GroupInfo.png'),
  Play: require('../Icon/Images/NewImage/play.png'),
  dw7: require('../Icon/Images/NewImage/n7.png'),
  GymImage: require('../Icon/Images/NewImage/GymImage.png'),
  Noimage: require('../Icon/Images/NewImage/no-pictures.png'),
  BlackCircle: require('../Icon/Images/NewImage/BlackCircle.png'),
  RedCircle: require('../Icon/Images/NewImage/RedCircle.png'),
  Heart: require('../Icon/Images/NewImage/Heart.png'),
  GreyCircle: require('../Icon/Images/NewImage/GreyCircle.png'),
  Watch: require('../Icon/Images/NewImage/watch.png'),
  Congrats: require('../Icon/Images/NewImage/Congrats.png'),
  Action: require('../Icon/Images/NewImage/Action.png'),
  Clock: require('../Icon/Images/NewImage/Clock.png'),
  Complete: require('../Icon/Images/NewImage/Complete.png'),
  Play2: require('../Icon/Images/NewImage/playButton.png'),
  Farwed: require('../Icon/Images/NewImage/Farwed.png'),
  Play3: require('../Icon/Images/NewImage/Play3.png'),
  Pause: require('../Icon/Images/NewImage/Pause.png'),
  Target: require('../Icon/Images/NewImage/Target.png'),
  Location: require('../Icon/Images/NewImage/Location.png'),
  WithoutEquipPerson: require('../Icon/Images/NewImage/WithoutEquipementPerson.png'),
  User: require('../Icon/Images/NewImage/User.png'),
  Boot: require('../Icon/Images/NewImage/Trainer1.png'),
  Send: require('../Icon/Images/NewImage/send.png'),
  Rest: require('../Icon/Images/NewImage2/restDay.png'),
  ChatHistory: require('../Icon/Images/NewImage/chatHistory.png'),
  Tick2: require('../Icon/Images/NewImage/Tick2.png'),
  Feedback: require('../Icon/Images/NewImage/Feedback.png'),
  Settings_v: require('../Icon/Images/NewImage/Settings_v.png'),
  Fire1: require('../Icon/Images/NewImage/Fire1.png'),
  Clock_p: require('../Icon/Images/NewImage/Chronometer.png'),
  Biceps_p: require('../Icon/Images/NewImage/biceps_p.png'),
  Pen_p: require('../Icon/Images/NewImage/Pen_p.png'),
  Down: require('../Icon/Images/NewImage/ArrowDown.png'),
  face0: require('../Icon/Images/NewImage/angry_p.png'),
  PurchaseTick: require('../Icon/Images/NewImage/PurchaseTick.png'),
  Clock1: require('../Icon/Images/NewImage/Clock1.png'),
  AppleLogo: require('../Icon/Images/NewImage/apple.png'),
  avt: require('../Icon/Images/NewImage/Avatar.png'),
  checked: require('../Icon/Images/NewImage/Check.png'),
  info: require('../Icon/Images/NewImage/info.png'),
  PaymentSucc: require('../Icon/Images/NewImage/PaymentSucc.png'),
  PaymentFaikd: require('../Icon/Images/NewImage/PaymentFaikd.png'),
  PadoDaolog: require('../Icon/Images/NewImage/PadoDailog.png'),
  Policy: require('../Icon/Images/NewImage/policy.png'),

  StartWorkoutButton: require('../Icon/Images/NewImage/StartWorkoutButton.png'),
  MyPlansWhite: require('../Icon/Images/NewImage/MyPlansWhite.png'),
  MyPlans: require('../Icon/Images/NewImage/MyPlans.png'),
  RedTick: require('../Icon/Images/NewImage2/GreenTick.png'),
  Location: require('../Icon/Images/NewImage/Location.png'),
  ClockGrey: require('../Icon/Images/NewImage/ClockGrey.png'),
  WeeklyPlay: require('../Icon/Images/NewImage/WeeklyPlay.png'),

  NewWorkout: require('../Icon/Images/NewImage2/NewWorkout.png'),
  Plus: require('../Icon/Images/NewImage2/plus.png'),
  Createworkout: require('../Icon/Images/NewImage2/createworkout.png'),
  Biceps: require('../Icon/Images/NewImage2/biceps.png'),
  CalenderNew: require('../Icon/Images/NewImage2/canender.png'),
  Search: require('../Icon/Images/NewImage2/search.png'),
  Plus: require('../Icon/Images/NewImage2/plus.png'),
  Minus: require('../Icon/Images/NewImage2/Minus.png'),
  BuildMuscle: require('../Icon/Images/NewImage2/BuildMuscle.png'),
  Strength: require('../Icon/Images/NewImage2/Strength.png'),
  WeightLoss: require('../Icon/Images/NewImage2/WeightLoss.png'),
  Experienced: require('../Icon/Images/NewImage2/award_star.png'),
  Begginer: require('../Icon/Images/NewImage2/electric_bolt.png'),
  AddIcon: require('../Icon/Images/NewImage2/G.png'),
  CreateW: require('../Icon/Images/NewImage2/create_new_folder.png'),
  Next: require('../Icon/Images/NewImage2/next.png'),
  Gym: require('../Icon/Images/NewImage2/Gym.png'),
  Home: require('../Icon/Images/NewImage2/Home.png'),
  Profile: require('../Icon/Images/NewImage2/Profile.png'),
  Workout: require('../Icon/Images/NewImage2/Workout.png'),
  Reports: require('../Icon/Images/NewImage2/Reports.png'),
  MyPlans: require('../Icon/Images/NewImage2/MyPlans.png'),
  HomeRed: require('../Icon/Images/NewImage2/HomeRed.png'),
  ProfileRed: require('../Icon/Images/NewImage2/ProfileRed.png'),
  WorkoutRed: require('../Icon/Images/NewImage2/WorkoutRed.png'),
  ReportsRed: require('../Icon/Images/NewImage2/ReportsRed.png'),
  MyPlansRed: require('../Icon/Images/NewImage2/MyPlansRed.png'),
  PlayIcon: require('../Icon/Images/NewImage2/PlayIcon.png'),
  NewPen: require('../Icon/Images/NewImage2/NewPen.png'),
  Bell: require('../Icon/Images/NewImage2/bell.png'),
  Planning: require('../Icon/Images/NewImage2/planning.png'),
  NewPrfile: require('../Icon/Images/NewImage2/NewProfile.png'),
  NSounds: require('../Icon/Images/NewImage2/NSounds.png'),
  NPedometer: require('../Icon/Images/NewImage2/NPdeometer.png'),
  NContact: require('../Icon/Images/NewImage2/NContact.png'),
  NPrivacy: require('../Icon/Images/NewImage2/NPrivacy.png'),
  NPolicy: require('../Icon/Images/NewImage2/NDocument.png'),
  NRate: require('../Icon/Images/NewImage2/NRate.png'),
  NDelete: require('../Icon/Images/NewImage2/NDelete.png'),
  NLogOut: require('../Icon/Images/NewImage2/NLogout.png'),
  NOWORKOUT: require('../Icon/Images/NewImage2/test.gif'),
  UpdateAppLottie: require('../Icon/Images/NewImage2/UpdateAppLottie.json'),
  DisplayOn: require('../Icon/Images/NewImage2/DisplayOn.png'),
  Exercise_Info: require('../Icon/Images/NewImage2/Exercise_Info.png'),
  Exercise_List: require('../Icon/Images/NewImage2/Exercise_List.png'),
  MaleNew: require('../Icon/Images/NewImage2/MaleN.png'),
  FemaleNew: require('../Icon/Images/NewImage2/FemaleNew.png'),
  Alert: require('../Icon/Images/NewImage2/Alert.png'),
  location_icon: require('../Icon/Images/NewImage2/location_searching.png'),
  location_ping: require('../Icon/Images/NewImage2/locationPing.png'),
  ModalCoin: require('../Icon/Images/NewImage2/ModalCoin.png'),
  Modal_img: require('../Icon/Images/NewImage2/Modal_img.png'),
  RecommendFitme:require('../Icon/Images/InAppRewards/RecommendFitme.png'),
  ChangePlan:require('../Icon/Images/InAppRewards/ChangePlan.png'),
  Trophy:require('../Icon/Images/InAppRewards/Trophy.png'),
  FitCoin:require('../Icon/Images/InAppRewards/FitCoin.png'),
  testbanner:require('../Icon/Images/InAppRewards/Banner.png'),
  completed:require('../Icon/Images/InAppRewards/Completed.png'),
  Missed:require('../Icon/Images/InAppRewards/Missed.png'),
  EditPen:require('../Icon/Images/InAppRewards/edit.png'),
  Rank1background:require('../Icon/Images/InAppRewards/Rank1background.png'),
  Coin:require('../Icon/Images/InAppRewards/Coin.png'),
  PinkGradient:require('../Icon/Images/InAppRewards/PinkGradient.png'),
  RedGradient:require('../Icon/Images/InAppRewards/RedGradient.png'),
  BlueGradient:require('../Icon/Images/InAppRewards/BlueGradient.png'),
  Top5Boundary:require('../Icon/Images/InAppRewards/Top5Boundary.png'),
  Winner:require('../Icon/Images/InAppRewards/Winner.png'),
  WinnerBackground:require('../Icon/Images/InAppRewards/WinnerBackground.png'),
  LoserBackground:require('../Icon/Images/InAppRewards/LoserBackground.png'),
  WorlCup:require('../Icon/Images/InAppRewards/WorlCup.png'),
  BasicPlan:require('../Icon/Images/InAppRewards/BasicPlan.png'),
  MediumPlan:require('../Icon/Images/InAppRewards/MediumPlan.png'),
  PremiumPlan:require('../Icon/Images/InAppRewards/PremiumPlan.png'),
  PlanBenifits:require('../Icon/Images/InAppRewards/PlanBenifits.png'),
  NameUpdateModal:require('../Icon/Images/InAppRewards/NameUpdateModal.png'),
  Reward_icon:require('../Icon/Images/InAppRewards/Reward_icon.png'),
  No_location:require('../Icon/Images/InAppRewards/No_location.png')
};
